--- arch/x86/Makefile
+++ arch/x86/Makefile
@@ -1,13 +1,17 @@
 # SPDX-License-Identifier: GPL-2.0
 # Unified Makefile for i386 and x86_64
 
-# select defconfig based on actual architecture
-ifeq ($(ARCH),x86)
-  ifeq ($(shell uname -m),x86_64)
-        KBUILD_DEFCONFIG := x86_64_defconfig
-  else
-        KBUILD_DEFCONFIG := i386_defconfig
-  endif
-else
-         KBUILD_DEFCONFIG := $(ARCH)_defconfig
-endif
+# select defconfig based on actual architecture, including wsl for x86_64 systems.
+ifeq ($(ARCH),x86)
+ifeq ($(shell uname -m),x86_64)
+ifeq ($(shell echo WSL_DISTRO_NAME),)
+       KBUILD_DEFCONFIG := x86_64_defconfig
+else
+       KBUILD_DEFCONFIG := wsl_x86_64_defconfig
+endif
+else
+       KBUILD_DEFCONFIG := i386_defconfig
+endif
+else
+       KBUILD_DEFCONFIG := $(ARCH)_defconfig
+endif
